### ISSUE TITLE
Trellis should initialize its own backend

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#196]
To the extent that any particular predefined information must be present in the repo backend for proper operation, `trellis-http` should take responsibility for inserting it if not present at startup time.

**Comment by ajs6f** [comment]
This could potentially happen in the constructor for `LdpResource`, so long as it is scoped to the application (or more narrowly).

**Comment by acoburn** [comment]
The triplestore- and db-based Trellis implementations both initialize the root container as so:

The following "server-managed" triples are added:

```turtle
<> a ldp:BasicContainer ;
    dc:modified "the-current-time"^^xsd:dateTime .
```

And the following "access control" triples are added:

```turtle
<#auth> acl:mode acl:Read, acl:Write, acl:Control ;
    acl:agentClass foaf:Agent ;
    acl:accessTo <> .
```

I suspect that the best interaction here would be as follows:

1. When the `LdpResource` constructor is called, it checks for the existence of a root container. 
2. If it doesn't exist, both the "server managed" and "access control" triples are added via `ResourceService::create` (specifying `ldp:BasicContainer` as the interaction model).
3. If, however, the resource does exist, but there are no access control triples (`Resource::hasAcl`), then just the access control triples will be added.

**Comment by acoburn** [comment]
Design-wise, I see a few possibilities here:

1. Have a `ResourceService::initialize` method (with a default implementation) that gets called by the HTTP layer. This would allow implementations to customize this step.
2. Have an extra parameter to the `LdpResource` constructor, accepting a collection or stream of `Quad`s (again, with a default implementation). This would allow assembled applications to customize this step.
3. Others?

I have a slight preference for the first option.

**Comment by DiegoPino** [comment]
@acoburn, same preference.

Question: Would/could `ResourceService::initialize` be exposed to the API? Kinda thinking it would be "neat" (new tech term for i have no real use case, but my mind says it makes sense) to allow deployer/implementer decide when/if this is invoked instead of letting the system go for the logic. Paranoid androids like me prefer a single extra call to some API to plant the seed than depend on logic i can not control to get it initialized. And just keep some state around that says "initialized/not yet". So basically if trellis does not find conditions for its root container, instead of going: "hey  i will deal with it" it logs the issue, does not start? and asks the a human to trigger the command? 

Again, not strong opinion really, just thinking about what can go wrong that could make trellis think it has no root container when it really has/had but momentarily something behind/inside/aside just died or is delayed.. but also just saying.. 🦊

**Comment by acoburn** [comment]
@DiegoPino there is definitely potential here for a race condition if multiple HTTP nodes are concurrently trying to initialize an eventually consistent back-end (or even multiple HTTP nodes sitting in front of a synchronous back-end). Either way, this `::initialize` operation would be idempotent, so even if multiple front-ends simultaneously try to write to a root container, the end result should still be the same.

**Comment by ajs6f** [comment]
We _could_ make that config'ble. I.e. a Java method to call from outside `trellis-http` and a switch that turns on "auto-boot" (calls that method with just the default root quads). It's up to impls to use or no.

I'll admit, I like that much less, because the responsibility for managing the use of that method is now on Trellis.

How about a policy object / policy method? So `ResourceService` now has something like a 
```
default Dataset initialDataset(Resource res) {
// build default quads as @acoburn describes above
}
```
which for our use case is called with the root, if "auto-boot" is on. Otherwise, some other component in the system that can get  hold of the `ResourceService` can do it manually:

**Comment by acoburn** [comment]
Effectively, something like this is going to need to be part of the `LdpResource` constructor (or as part of a `@PostConstruct` annotation):

```java
resourceService.get(rootResource)
	.thenCompose(res -> {
                final Dataset dataset = buildDefaultAclDataset();
		if (MISSING_RESOURCE.equals(res) || DELETED_RESOURCE.equals(res)) {
			LOGGER.info("Initializing root resource");
			return resourceService.create(rootResource, session, LDP.BasicContainer, dataset, null, null);
		} else if (!res.hasAcl()) {
			LOGGER.info("Initializing root resource ACL");
			res.stream(PreferUserManaged).forEach(dataset::add);
			return resourceService.create(res.getIdentifier(), session, res.getInteractionModel(), dataset, null, null);
		}
		return completedFuture(null);
	}).join();```

The `buildDefaultAclDataset()` really only needs to contain the following in the `PreferAccessControl` graph:

```turtle
<#auth> acl:mode acl:Read, acl:Write, acl:Control ;
    acl:agentClass foaf:Agent ;
    acl:accessTo <> .
```

And that's a pretty standard "generic wide-open WebAC authorization", so do we let that be customizable? Or should that be the default ACL (which a user/admin can modify manually via SPARQL-update?)

@ajs6f would you like to suggest an impl for this, or shall I take a stab at it? (or anyone else, for that matter!). A real impl of this would need to make sure the `Dataset` actually gets closed via the `CompletableFuture::whenComplete` method, and it would probably make sense to use the `TrellisDataset` class, since that won't throw a checked exception on `::close`.
