### ISSUE TITLE
How even _am_ versioning?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#206]
Okay, a question about resource versioning and the Java SPI.

Looking at `MementoService`, the parallels to `ResourceService` are obvious (modulo `Session`, which doesn't matter modulo time). But how are these two services used together?

Can resource creation occur via `MementoService`, or only `ResourceService`? This matters particularly because it affects persistence strongly. Is `MementoService` really a kind of `ResourceService` just with the additional semantics of that last `Instant` parameter, so to speak?

Are all resources versioned, or only some, and if only some, how does a backend know which ones?

Thanks for any light shed here!

**Comment by acoburn** [comment]
The two services are designed in such a way that the persistence layers for each can be completely separate. For instance, you could conceivably store resources in a database-type system (RDBMS, triplestore, cassandra, etc) and store mementos in more of a BLOB-style system (files, cloud storage, etc). Though you could also combine the two, if desired, putting everything into a single persistence layer.

The HTTP layer manages the creation of Mementos, which happens whenever the resource itself is modified, but this only applies to direct resource modification; any changes to ancillary resources (i.e. modifications to containment or membership triples) do not generate new Mementos for those resources. For example, if you create an LDP-RS inside of a containter, a new memento will be created for that LDP-RS, but not for the parent container (even though the container itself changes).

The relevant memento creation code is [here](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java#L106-L114), which basically does a full read on an existing resource and writes the contents directly into the memento subsystem. Now, if the ResourceService and MementoService have a shared implementation, one could get clever about this and make that `MementoService::put` method technically a no-op and manage the memento creation inside of the `ResourceService` methods themselves.

While resource creation needs to happen via the `ResourceService` interface, it is also true that the `MementoService` is just a specialized type of `ResourceService` (though with slightly different method names).

As far as which resources get versioned: basically all resources are versioned, but as described above, not all resource changes lead to new Mementos.

The one `MementoService` [implementation](https://github.com/trellis-ldp/trellis/blob/master/components/file/src/main/java/org/trellisldp/file/FileMementoService.java) that I have really just takes a stream of quads and writes them to a file of n-quads. And it will read those back into a `Stream<Quad>`. The one method here that's really different from the `ResourceService` is the method that lists the available Mementos -- this should be suitably fast since it gets called on every `GET` request, generating the appropriate Memento-related headers.

Trellis takes no stance on anything a service might do internally to prune out unwanted Mementos. E.g. you may have a policy to keep every Memento from the last month, but only one per week from the last year, etc. Trellis will just list the Mementos that the service claims exist. You'll remember from the no-op impl, that it just discards all the write requests and returns an empty collection when asked to list the Mementos.

**Comment by acoburn** [comment]
Yes, unless you have a particular need to coordinate the management of Mementos and Resources, I'd definitely recommend keeping the two services separate.

**Comment by ajs6f** [comment]
Excellent!
