### ISSUE TITLE
Trellis assumes that IRI hierarchy represents extant containment hierarchy for new resources

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#214]
Mouthful of a title there.

Trellis (in the HTTP layer) assumes that if a resource that it is creating from `PUT` has an IRI that features a more leftward segment, it exists as a container. E.g. `http://example.com/trellis/somestuff/myresource` shows
`http://example.com/trellis/somestuff` as a "subterm" and Trellis then assumes that `http://example.com/trellis/somestuff` exists (from the IRI) and assigns it as a container to `myresource`, using the normal call it makes to `ResourceService::create`. But `somestuff` is not there and a `GET` issued there returns 404 because it was never actually created.

We can play this several ways. Some people would like to do "`mkdir -p`". I think that's terribly wrong. I would rather be able to use `PUT` to make uncontained resources. In any event, the current behavior can't be right. Either we should actually create `somestuff` or not.

**Comment by acoburn** [comment]
It turns out that using PUT to create resources is really complicated. I'm even of a mind to just disable that, but I think that would be an overreaction.

From one perspective, if, in a highly distributed Trellis deployment you create two resources via PUT: `http://example.com/somestuff` (an LDP-C) and `http://example.com/somestuff/myresource` (an LDP-RS), who is to say that `/somestuff` is actually persisted before `/somestuff/myresource`? So what Trellis tries to do (this is how it works for the existing persistence layers) is this: when the child resource is created, it acts as if the parent resource also exists (and if it doesn't exist, it assumes that it will exist soon); if, at some later point, that parent resource springs into existence, it will have containment triples pointing to that child resource.

This has several curious side-effects. First, if the parent resource isn't a container, then those containment triples need to be ignored, and that's what the current impls do. Or if the parent starts out as a Container but then is deleted and later replaced with an LDP-NR -- containment triples don't make any sense in that context. There's also the case that the parent resource may never be created.

This is where LDP sits a little uncomfortably with REST: should the creation of a `/somestuff/myresource` resource also create a `/somestuff` resource if that resource didn't previously exist? I've generally come down on the side of no, ancillary resources should not be created or deleted just because some other resource was created or deleted.

Still, that leaves a sufficient amount of ambiguity about the proper behavior here. And I am definitely open to suggestions!

**Comment by ajs6f** [comment]
Yes, that's why I'm saying "`mkdir -p`" is wrong here. It's unRESTful. And I'm confident that the approach that is simplest and least likely to go wrong is to do nothing. Don't create or assume the creation of the container, don't add triples that no user ever made. If `PUT` always creates an uncontained resource, the problem dissolves. Using two `PUT`s to create two resources then has but one unambiguous interpretation-- that no containment is intended. A `PUT` and then a `POST` (potentially with slug) would be the alternative.

This could be as simple as removing this action from `PUT` and making sure that `POST` throws error responses if sent to a non-existent container. I should think the latter is already the case, no?

**Comment by acoburn** [comment]
As in: when using `PUT` to create a resource, the method passes a `null` value for the `container` property. That is easy to do.

The question then becomes: if a `PUT` request is updating an existing resource, does the `container` argument get null (if it had previously been null) or does it get some value (if it had been created via POST).

I think what we need here is a new method: `Resource::getContainer` which returns an `Optional<IRI>`. This way, when replacing an extant resource, that resource will know whether it has a parent or not.

**Comment by ajs6f** [comment]
Yes, that's what I want out of `PUT`s that create. 

I equipped my impl of `Resource` with that method already, for my own convenience, but I don't think we have to add it if we use `ResourceService::getContainer`, do we? I agree that for extant resources, we should avoid changing the parent without some explicit gesture from a client that so directs the server, and that `PUT` alone isn't enough. Do we need a way for people to remove things from a container without `DELETE`ing them? I don't know that we do. That's perilously close to WebDAV's `MOVE`, and I sure don't want to go there.

**Comment by acoburn** [comment]
This also raises issues for WebAC, which relies on a containment hierarchy, and if there is no parent for a resource, it _must_ find an ACL there (unless we have some other mechanism for defaulting to some central ACL). The current code just assumes that everything exists in a containment structure until it gets to the root of the repo -- which is also problematic. There are problems all around once you introduce a disconnected resource graph, but you've also got to allow for this with a distributed persistence layer.

The same issues applies (in reverse) to DELETE when operating on a container that has child resources.

Still, I think we can get this to work with a `Resource::getContainer` method. I don't know if that obviates the need for `ResourceService::getContainer` or not; I'll need to check the code.
