### ISSUE TITLE
Return values for mutating methods

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#218]
Currently, methods on `MutableDataService` all return `CompletableFuture<Void>`. What do you think of `CompletableFuture<? extends Resource>` instead, where the value is either the previous or current state of the resource in question?

**Comment by ajs6f** [comment]
For the former, `::create`ing a resource would return `MISSING_RESOURCE` or `DELETED_RESOURCE` as appropriate, or just `MISSING_RESOURCE`, at the backend's discretion.

**Comment by acoburn** [comment]
Do you have a particular use case in mind for this? Typically, a mutating method returns no body in HTTP (`201 Created` or `204 No Content`), so there isn't a strict need for the resulting resource.

That said, in principle, this could be useful when a client sends a mutation request along with a `Prefer` header (i.e. `return=representation`), which is currently possible with `PATCH`.

**Comment by ajs6f** [comment]
That latter is what I was thinking of-- situations where we _do_ want to know the resource, immediately. Not a huge gain. `-http` is the primary client of the Java SPI, of course, and if you don't see much gain there, we can close this.

**Comment by acoburn** [comment]
The HTTP layer will already have all the information it needs w/r/t the user-managed triples in a resource representation (since that's what is sent to the `ResourceService` methods). What that data layer doesn't posses is information about containment and membership triples. _If_ the backend system is synchronous, then returning a full `Resource` would provide that; however, if the backend isn't synchronous, it could introduce some confusion about expectations.

For example, if containment/membership triples are computed asynchronously or if a persistence layer is eventually consistent, those triples may not be available immediately. When I wrote the Kafka-based implementation, the user-managed triples were written synchronously but the containment/membership triples were written asynchronously.

I mostly see the value here in the context of `PATCH`. With `PUT` or `POST` a client will already have the full set of user-managed triples in hand.

In a word: this is already (more or less) supported for `PATCH` in the HTTP layer, and I wonder whether changing the return types would introduce a false set of expectations.

**Comment by ajs6f** [comment]
Well, I would think people would understand the asynchrony from the `CompletableFuture`, but like we said, it's only a gain if we have a  use for the results, and if you don't need them in `-http`, we don't need 'em.
