### ISSUE TITLE
Memento and Binaries

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#245]
I see methods in `MementoService` for managing `Resource`s, but not `Binary`s. Is the mechanism that a fresh `Binary` is created for every new Memento of a NonRDFSource, and the connections in time are made among the `Resource`s that reference those `Binary`s?

**Comment by acoburn** [comment]
Basically yes. Each `NonRDFSource` has a unique identifier that is handled by the underlying `BinaryService`. If one were to `PUT` a new binary resource, a new identifier would be created for that binary, and so the Memento for the first version would point to the first binary identifier and the second version would point to the second binary.

**Comment by ajs6f** [comment]
Cool, that makes sense.

**Comment by ajs6f** [comment]
Further question: we offer a `MementoService::delete` method. Do we need to write down our assumptions about GC? If the last resource (a Memento) connected to a `Binary` is deleted, should the backend be permitted to delete the `Binary`?

**Comment by acoburn** [comment]
This is precisely what makes `::delete` difficult, whether it's in the `MementoService` or the `ResourceService`: knowing when a binary resource can be deleted. At present, this issue is sidestepped by just _not_ allowing clients to delete Mementos, hence Binaries are never deleted. In fact, there used to be a `ResourceService::purge` [method](https://trellis-ldp.github.io/trellis/apidocs/org/trellisldp/api/ResourceService.html#purge-org.apache.commons.rdf.api.IRI-) that returned a `Stream<IRI>`, containing the identifiers of Binary resources that could be safely deleted. That method has been removed from `master` in part because it was not tied to the HTTP layer in any way but also partly because the entire design of _resource deletion_ needs further examination.

For the 0.8 release, I am somewhat inclined to just _remove_ all the delete-related methods. I would like to see them restored in a subsequent release (0.9?) but only after we figure out exactly what `::delete` really means.

Part of the challenge has to do with the fact that binary resources are loosely coupled to the other services by means of an IRI. That loose coupling hash a lot of advantages, but it also means that a given IRI may be referenced by the MementoService, the ResourceService, both or neither. There is also no efficient mechanism to determine which resources/mementos refer to a given Binary resource.

**Comment by ajs6f** [comment]
> For the 0.8 release, I am somewhat inclined to just remove all the delete-related methods.

This.

**Comment by ajs6f** [comment]
More seriously, all this jazz about delete semantics seems to me (for the moment at least) to be something we can throw into the laps of the backends, while muttering something about "Let a hundred flowers bloom, laboratories of democracy, strength from diversity, etc."

**Comment by acoburn** [comment]
For now, yes, let's leave `::delete` entirely out of the interface and let the backends manage that.

**Comment by acoburn** [comment]
Are you satisfied with where this stands for now? I.e. can we close this issue?

**Comment by ajs6f** [comment]
Yyyyyyup.
