### ISSUE TITLE
Review ResourceService interface

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#278]
The `ResourceService` interface (actually the `MutableDataService`) has two methods with identical signatures: `::create` and `::replace`. In evaluating the full code paths in the DB- and Triplestore-implementations, the two methods behave _exactly_ the same. In fact, the only difference is that one contains `LOGGER.debug("Creating resource {}", identifier)` while the other has `LOGGER.debug("Replacing resource {}", identifier)`.

Originally, these methods were unified under `::put`, but they were split apart to make it easier to handle different event types (update vs. create). But now that event handling has been moved out of the `ResourceService` and into the HTTP layer, it seems that this separation is no longer necessary.

Are there other considerations here? Or would it be possible to consolidate those methods into a single `::put` method?

**Comment by ajs6f** [comment]
They are the same in `-cassandra`, too. I can imagine backends, tho, that would want to distinguish them. Those that mutate their contents (instead of only adding to them) might want to understand that at call time, or suffer the penalty of read-before-write (which is not the worst fate in the world, but is a performance drag).

**Comment by acoburn** [comment]
OK, let's leave this interface as it is.

**Comment by ajs6f** [comment]
We certainly can-- one other option would be to play it out with `default`:

```
default CompletableFuture<Void> create(IRI identifier, IRI ixnModel, Dataset dataset, IRI container, Binary binary) {
    return replace(etc.etc.etc.);
}

CompletableFuture<Void> replace(IRI identifier, IRI ixnModel, Dataset dataset, IRI container, Binary binary);

```

**Comment by acoburn** [comment]
Actually, I really like that idea: `create` defaults to `replace`, but it allows an impl to override that if necessary.

**Comment by ajs6f** [comment]
Some of this came out of our desire to translate LDP/HTTP as directly as possible. In that light, `create` could be `POST` or `PUT` and `replace` could only be `PUT`. But from the POV of the client (meaning `trellis-http`) in both cases, the expected behavior is exactly the same; "I don't care what was there before, make sure that _this_ is there now." To the extent that a backend has to know what was there before to do the job properly, it's reasonable of use to provide a hint to that effect, and I'd really rather not shove that too into the params. That's the kind of info (recording, as it does, not a transportable datum, but a condition) that belongs in the call stack in a language like Java.
