### ISSUE TITLE
Binary modified vs. resource modified

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#288]
Checking through some of the binary-related test code, I have come to realize something that wasn't clear to me (I think).

Am I correct to assume that for a given LDP-NR, the modification date of the binary and the modification date of the description must be maintained separately by the backend? The tests seem to be comparing ETags and expecting that to be the case.

TBC, that makes sense with what I know of ETags, I just want to confirm it here, because by gum, there is a lot of confusion over the relationship between things and their descriptions in LDP, and we don't want to add to that.

**Comment by ajs6f** [comment]
Jsut to be a little more clear, this is what I understand to be indicated by the difference between `Resource::getModified` and `someResource.getBinary()::getModified`.

**Comment by acoburn** [comment]
Yes, those are two distinct values. If a description is updated, then the `Binary::getModified` value wouldn't change (though the `Resource::getModified` would). If the binary itself is updated (e.g. via `PUT`, then -- IIRC -- both values get updated, though you shouldn't expect that those values would be the same).

**Comment by ajs6f** [comment]
Okay, I now suspect that this issue may be related to https://github.com/trellis-ldp/trellis/issues/287, via the following question: for the `MementoService::mementos` method, _which of the two possible mod-dates is to be reported_? Is it a case of "use the main date for RDFSources, but the binary date for NonRDFSources"?

**Comment by acoburn** [comment]
This needs to be confirmed, but if I'm not mistaken, a new (RDF-based) Memento is written whenever a binary or its description is changed. So, the memento service should be using the main date for RDFSources.

**Comment by acoburn** [comment]
I think there may be an issue lurking here. Basically, the DateTime value of the Binary is going to be different than the DateTime value of the RDFSource (upon creation). And if that value varies by more than a second, the values of the TimeMap and/or Memento headers may be misleading.

The issue is also one of design: for Binaries, the modified datetime is set in the [HTTP layer](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/impl/PostHandler.java#L185), while the resource/description is set in the [persistence implementation](https://github.com/trellis-ldp/trellis/blob/master/components/triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java#L167)

One option would be to override whatever was initially set as a modification time on the `Binary` object (at creation time) inside the persistence layer. That is, the HTTP layer would set a provisional modification time for the binary, but the persistence layer would have ultimate say over how that is stored. My initial thought is that this seems cumbersome, brittle and error-prone.

Another option is to go back to having an `Instant` parameter on the various mutating `ResourceService` methods. That way, all writes would get the same modification value, as set in the HTTP layer -- the value would be derived from the `session` field in the `http.impl.MutatingLdpHandler` class. To me, this seems like the cleanest solution.

**Comment by ajs6f** [comment]
> The issue is also one of design: for Binaries, the modified datetime is set in the HTTP layer, while the resource/description is set in the persistence implementation

This is exactly what was troubling me. I'm glad it wasn't just me noticing that.

>  And if that value varies by more than a second, the values of the TimeMap and/or Memento headers may be misleading.

That's to the client. For testing, we might even want to work directly against the `Instant`s in some cases, and that ain't going to fly at all right now.

As for the right design... I'm not sure whether I'm okay with having HTTP fire in the date-times. I'm trying to understand if that would be confusing to clients in situations of significant asynchrony. Suppose you fire a request at t=1sec, it persists at t=5sec, then you get back the mod-date (via a later `GET`) of t=1sec. Now you have a badly mistaken understanding of what actually happened on your network and for purposes of debugging or auditing you are really starting off wrong-footed. Yes, you'll figure it out soon enough, but we sent you down the wrong road at the beginning.

What about the opposite approach? Drop the `Binary::getModified` method and provide two `getModified` methods on `Resource`, something like `getMetadataModified` and `getBinarydataModified` (okay, we'd need better names) that are both controlled by the backend?

I mean, we could go all the way to four methods (`getMetadataModifiedFromRequest`, `getBinarydataModifiedFromRequest`, `getMetadataModifiedAsPersisted`, `getBinarydataModifiedAsPersisted`). I'm not for a moment seriously suggesting that-- my point is that we start with that panoply, and we have to cut it down and/or package it to the point that it's accurate _and_ useful. My contention is that the `AsPersisted` are ultimately the most important, but that's from a whole-systems POV.

**Comment by acoburn** [comment]
I like the direction of this suggestion. In a certain sense, the `ResourceService::getBinary` is already a sort of "binary metadata". The issue is that `Binary` is a class, not an interface, and that class requires an `Instant` in its constructor. What if we change that -- either making `Binary` an interface and having an impl in the HTTP layer -- one that doesn't accept an `Instant` (and which errors if `::getModified` is called; something like: `NonPersistedBinary`). And then the persistence layer would impl its own `Binary` class (e.g. `PersistedBinary`). With the triplestore and db impls, the ResourceService is already managing that binary modification date, but the key thing would be to make the interfaces clear to someone writing their own persistence layer.

**Comment by ajs6f** [comment]
Well, either `Binary` could become an interface, or it could become a quartet of `Optional<T>` accessors on `Resource`, which comes to the same thing… in some ways, I prefer factoring it into `Resource`, for which backends must already supply impls.

`-cassandra` is also already managing the binary mod-date, because (I think) every impl must.

**Comment by acoburn** [comment]
The advantage of keeping `Binary` (even as a class) is that it reduces the number of arguments on the mutating `ResourceService` methods. One possibility would be to simply remove the `Binary::getModified` method from the class and then add a `Optional<Instant> Resource::getBinaryModified()` method.

**Comment by ajs6f** [comment]
Yes, that's true, and they are long enough already. But by the logic you give above, shouldn't we discard the idea (introduced between https://github.com/trellis-ldp/trellis/issues/263#issuecomment-435604562 and https://github.com/trellis-ldp/trellis/issues/263#issuecomment-435692570) that a `Resource` instance is always in management? This arises from the argument (a minore ad maius) you make about `Binary`s, to let us say that HTTP could pass `NonPersistedResource`s to `ResourceService`.

That would _really_ cut down the params. :)

**Comment by ajs6f** [comment]
Wait, isn't that what I suggested in https://github.com/trellis-ldp/trellis/issues/288#issuecomment-437139290 ?

**Comment by ajs6f** [comment]
Come to think of it, maybe we should block here on your investigations into https://github.com/trellis-ldp/trellis/issues/287 . I suspect they may be illuminating, one way or another.

**Comment by acoburn** [comment]
Yes, #287 is definitely related here. What I'm thinking is this:

I'd like to introduce a new interface: `ResourceTemplate` -- this gets an implementation in the HTTP layer (or maybe a default impl in the api layer), and the mutable `ResourceService` methods accept that as a parameter. Then, the `Resource` interface stays exactly the same. This is basically just a variation on https://github.com/trellis-ldp/trellis/issues/288#issuecomment-437152129

With this structure, modification dates are completely controlled by the persistence layer: the HTTP layer stays completely out of it.

**Comment by ajs6f** [comment]
So `ResourceTemplate` is "filled in" by a `ResourceService` (which gets it as a method param) to generate a `Resource`. When the future returned from that method competes with that `Resource`, that implies that the data therein is now managed by that `ResourceService`. Correct?

**Comment by acoburn** [comment]
Yes, that is how I am thinking about this. I am also thinking that this would only apply to the `::create` and `::replace` methods.

**Comment by ajs6f** [comment]
It sounds good. I'm assuming that `ResourceTemplate` would have everything that `Resource` does, including a `Stream` of content, save for the problematic timestamps.

I'd be very happy to code to this!
