### ISSUE TITLE
"Live"ness in different places

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#300]
Currently, Trellis has no overall policy about the "live"ness of data, but in several implementations, we've independently chosen to have metadata in state in `Resource` impls, but tuples come "live".

Suppose at t=0 I call `Resource:Service::get` and then hold onto my `Resource` until t=2 before calling `stream` on it. In the meantime, at t=1, another request completes to alter that resource. Now the original client is getting metadata from t=0 and quads from t=1.

Problem?

**Comment by acoburn** [comment]
Is this a problem? One could view this as a form of eventual consistency, and if the backend is already eventually consistent, then this is already going to be an issue for clients.

I am trying to understand where this would result in a problem, though. For example, if the resource ETag is generated for at t=0, the data are output at t=2, a client modifies those data, and then tries to `PUT` the modified data back into the system with an `If-Match` header. That request would fail because the ETag state would have shifted under the client's feet (even though the client technically is working with good data). In that case, a `412 Precondition Failed` would be returned and the client would try again (which is a pretty normal workflow).

Another place where this could be an issue for a client is where, at t=1, the resource is deleted and so some partial (or non-existent) response would follow at t=2.

Personally, I don't see this as a problem, though being clearer in the documentation would make sense to me.

**Comment by ajs6f** [comment]
I'm thinking of multiple (JVM) clients to the service, not multiple (HTTP) clients to the server, but if we just want to rule that out (declare that any `ResourceService` instance is usable only from some well-defined scope that presumably be in-JVM), that works for me.

**Comment by ajs6f** [comment]
Hang on, now I read your comment more carefully, I think we might be talking about two different things. You write, "a client modifies those data" and everything after that, but no, I meant that by the time the client has received the data, the damage is done, because it may take action somewhere else (in some other part of the system entirely) based on headers from t=0 and body from t=1. IOW, the mismatch is not between two responses-- it's between two pieces of one response.

**Comment by ajs6f** [comment]
Ok, I'm good with the answer that we don't make that guarantee, but I think we ought to be pretty loud and proud about it. It's going to be unexpected to some devs.

**Comment by acoburn** [comment]
https://github.com/trellis-ldp/trellis/wiki/Trellis-Architecture/_compare/416e324d382bd46d086bb80c44cd0e730a831e43...7b451e89081bcd7516a604a966d69be8fcfb32bc
