### ISSUE TITLE
Reconsider Commons RDF

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#32]
I'd like to understand the value being added to Trellis by the use of Commons RDF. Using it introduces a _huge_ number of short-lived objects, the project isn't very responsive, and the only implementation that we actually use so far is `commons-rdf-jena`. Is the expectation that people writing new modules for Trellis might want to use RDF4J or some more obscure RDF framework?

**Comment by acoburn** [comment]
This is a very good question. This also goes to the question of what _is_ Trellis. The initial concept of Trellis was to provide a collection of common interfaces for writing an LDP + Memento + etc server. That is, it really consists of just `trellis-api`, `trellis-http` and `trellis-vocabulary`. All of the rest is (really) just gravy.

And so part of the value of those interfaces is in their _lack_ of particular dependencies. Of course there are some dependencies, but they are pretty minimal (mostly Apache commons).

This means, for example, that the serialization layer can be considered independent of the HTTP layer, which can be independent of the persistence layer. Much of this is guided by previous experience trying to decouple these layers in software with deeply complected structure. And that structure became, ultimately, unmaintainable.

I realize that commons-rdf is pretty slow-moving and unresponsive, and I am concerned about that. But there is also (in a strange way) some value in having those underlying components be slow-moving, since it makes it easier to build on top of them. The bigger concern from my perspective would be that of short-lived objects and GC performance, generally. If it appears that commons-rdf is a significant performance bottleneck, I would be entirely in favor of re-evaluating it's role in Trellis. But I would like to see more real-world performance metrics before making a such a major change.

**Comment by ajs6f** [comment]
Certainly, we want to see numbers before optimizing. Rereading what I wrote, I think "lots of short-lived objects" was my passive-aggressive way of saying, "I'm tired of writing reams of logic-free conversion code every time I need to do something more complex with RDF than put it into and take it out of simple containers." (Including, say, writing it down or reading it.)

What I would offer as an alternative is _not_ to go whole-hog into a big framework like Jena or RDF4J, but just to use the core API from such a system and whatever SPARQL functionality might be needed for drive.

But I'm content to just make the remark now and we can revisit in a few months or so.

**Comment by acoburn** [comment]
So far, I've found that there are two parts of the code where a specific framework is needed: serialization and persistence. Everything else remains firmly rooted in the `commons-rdf-api` interfaces. But in writing a new persistence layer, I would expect a bit of conversion between Commons-RDF objects and Jena/RDF4J objects.

**Comment by ajs6f** [comment]
Yes, that I would expect. But that (serialization and persistence) is the bulk of the work now that you cut the HTTP layer! :) I suggest we go forward and after we deal with the problem of wiring, this issue may look very different (for better or ill). Shall I close it until then?

**Comment by acoburn** [comment]
Sure you can close the issue for now. But yes, let's revisit this later.

**Comment by ajs6f** [comment]
Closing for the while as discussed above.
