### ISSUE TITLE
Consider using `CompletionStage` for asynchrony

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#323]
Currently we use `AsyncResponse` for HTTP asynchrony in `trellis-http`. Because of our `CompletionStage`-based Java SPI, it might make more sense to switch to a [`CompletionStage`-based](https://dzone.com/articles/completionstage-support-in-server-side-jax-rs) API instead.

**Comment by acoburn** [comment]
Is there a particular advantage to returning a `CompletionStage` over doing what we [currently have](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java#L175-L178):

    future.thenApply(asyncResponse::resume);

**Comment by ajs6f** [comment]
Yes, we would drop the `@Suspended final AsyncResponse response` from the signature (less intrusion from frameworks into our code) and the heavy building going on in `TrellisHttpResource::fetchResource` could get replaced with a JAX-RS `MessageBodyWriter`, which to my mind is much easier to read and idiomatic. I never like to see JAX-RS controller methods returning `void` or `Response` or the like. Better to have semantically-meaningful types in those slots.

**Comment by acoburn** [comment]
I'm all for using idiomatic code. My only question is that, as I understand `AsyncResponse`, this allows the application container to separate the pool of request handling threads from the pool of worker (i.e. response generating) threads. That is, under heavy load, we'd want to pass the incoming requests off to a worker thread as soon as possible; otherwise, the request handler ends up blocking while the response is being generated, and during that time, the request handler can't process other incoming connections.

**Comment by ajs6f** [comment]
Yes, and the same function (so to speak) is provided in the `CompleteableFuture` design by the slot for an `Executor` in the various `*Async` methods of `CompletionStage` , e.g.
```
thenApplyAsync(Function<? super T, ? extends U>, Executor)
```
In `t-c*`, e.g., I put threadpools in those slots, which is what disconnect the original (request-serving) thread from the threads that do IO with C* and compute things like digests.

**Comment by acoburn** [comment]
I took a look at this, and yes, it will be trivial to implement. However, we'll need to wait a bit on adding this to the codebase. The issue is that Jersey supports a `CompletionStage<T>` based API starting with version 2.27, but dropwizard still uses 2.25. Jersey has been upgraded to 2.27 in dropwizard's `master` branch, so once they cut their next release from master, we can move ahead with this. In principle, I could force dropwizard to use a newer version of jersey, but that seems ill-advised given that the commit wasn't just a simple bump of the version number in the `pom.xml` file.

**Comment by ajs6f** [comment]
This is ultra-low-priority. Juggling versions against Dropwizard vitiates the whole gain of it. Let's relax and let them do the coding for us.

**Comment by acoburn** [comment]
No, Dropwizard does not have an updated version of Jersey. My plan is this: once 0.8 is released, I'd like to move entirely away from Dropwizard and adopt a MicroProfile-based deployment option. That will buy us a huge amount of flexibility, and at that point, this issue becomes easier to deal with.

**Comment by ajs6f** [comment]
Okay, I'll consider this blocked on #209. Which is to say, I'll go take a look at #209.
