### ISSUE TITLE
Superclass for `*HandlerTest`?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#33]
There are `*HandlerTest`s for all the various `PutHandler`, `DeleteHandler`, etc. I suspect (might be wrong!) that we could abstract over them and pull up some of the tests using some generics tricks, and this issue is a note to self to try it.

**Comment by acoburn** [comment]
That sounds great. One thing to mention is that most of the HTTP-layer is tested via the `AbstractLdpResourceTest`, which is a crazy large file. The `*HandlerTest`s are, comparatively, pretty manageable, but feel free to refactor the tests as needed.

If you do decide to tackle the `AbstractLdpResourceTest` file, it might also be worthwhile to break that up into smaller classes that get assembled into a single abstraction. Another thought I've had is to abstract out a lot of the testing infrastructure into the (currently very small) `trellis-test` module. The idea would be that, for a given implementation of a Trellis service, the tests would mostly be written. So for an alternate impl of the persistence layer, you could re-use all of those tests.

Realistically, in order to make that work, it's likely that the current PaxExam tests in `trellis-test` would need to be pulled out and put into a `trellis-itest` module (I could be wrong here, but we may need to do this in order to avoid cyclical dependencies).

**Comment by ajs6f** [comment]
Am I missing something here? The only tests I see in `trellis-test` are just installing features into Karaf...

**Comment by acoburn** [comment]
No, you aren't missing anything. That's the only test there at present. I was only describing a possible future expansion of the scope of that module.

**Comment by ajs6f** [comment]
Cool. I do like the idea of strongly distinguishing between unit tests, integration tests, and system tests.

**Comment by acoburn** [comment]
@ajs6f are you still planning on working this one? Is it still relevant?
Thanks.

**Comment by ajs6f** [comment]
Urg. I am not sure if it is relevant, because the code has changed a lot. I am not going to get to it anytime in the next month, for sure. I'm fine with closing it for now.

**Comment by acoburn** [comment]
OK that's cool. I'm all for refactoring the code where it makes sense, and we can definitely revisit this later if it is relevant.
