### ISSUE TITLE
Trellis not listed in LDP implementations?

### ISSUE THREAD

**Issue by pmcb55** [trellis-ldp/trellis#365]
Hi,

I've been very impressed from my initial look at Trellis, and was just wondering if there's any reason it's not listed in the 'official' W3C list of LDP implementations here: https://www.w3.org/wiki/LDP_Implementations?

Thanks,

Pat.

**Comment by acoburn** [comment]
This is a great idea. I'll figure out how to get Trellis listed there.

**Comment by acoburn** [comment]
@ajs6f do you have write access to the page at https://www.w3.org/wiki/LDP_Implementations?

It seems that I'd need to be a full W3C member in order to modify that page.

What we'd want to add is, effectively, this:

## TrellisLDP (Server)
**Summary**
A horizontally distributable, high-performance LDP implementation. Also supports [Memento](https://tools.ietf.org/html/rfc7089), [WebAccessControl](http://www.w3.org/wiki/WebAccessControl) and [ActivityStreams](https://www.w3.org/TR/activitystreams-core/).

**Website**
[https://www.trellisldp.org](https://www.trellisldp.org)

**Contact**
Aaron Coburn

**Status**
Initial release 2018, under active development

**Timeline**
Full LDP 1.0 compliance since 2018

**License**
[Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)

**Platform**
JavaEE

**Language**
Java

**Comment by ajs6f** [comment]
I don't know, but I will check this evening Eastern. If not, we know people who do, so there's no obstacle.

**Comment by ajs6f** [comment]
Done with https://www.w3.org/wiki/index.php?title=LDP_Implementations&oldid=109038
