### ISSUE TITLE
Switch from Tamaya API to MicroProfile Config

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#366]
Tamaya, while excellent software, does not seem likely to produce its own long-lasting API. What is more, it already can implement MicroProfile Config (including injection). We should switch to code against µP Config's API, using Tamaya to implement it.

**Comment by ajs6f** [comment]
How does this play against https://github.com/trellis-ldp/trellis/issues/337?

**Comment by acoburn** [comment]
My opinion is that this issue supersedes #337. Since the tamaya-microprofile artifact won't be available until the 0.4 release, we'll need to use some other µP-config implementation until then. By switching to µP-config, we should have a lot of flexibility around config implementations, and if (once Tamaya 0.4 is released) we want to go back to Tamaya, we can do that. Does that sound right?

**Comment by ajs6f** [comment]
Well, that's the question. Is it better to wait for Tamaya 0.4, then switch? Less fuss, more delay...
