### ISSUE TITLE
Construct an Amazon AMI

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#367]
We should be able to deploy Trellis via an AMI with an arbitrary backend cluster, also provided by AMIs.

**Comment by acoburn** [comment]
Rather than generating an AMI, it might make more sense to use the [Amazon Elastic Container Service](https://aws.amazon.com/ecs/) and/or [AWS Fargate](https://aws.amazon.com/fargate/), using the Docker containers that we're already publishing.

A related option would be to publish a CloudFormation template, making it easier to deploy Trellis as a complete stack. We should also consider publishing a Kubernetes configuration (or, even better, a `helm` template). I think the goal here should be: easy deployment in AWS/GCP/Azure as well as in an arbitrary Kubernetes cluster.

**Comment by ajs6f** [comment]
Right on. I'm not familiar with the state of offerings here, but your stated goal is very much what I wanted to raise in this issue. With respect to Kubernetes, [Quarkus](https://quarkus.io/) may turn out to be interesting.

**Comment by acoburn** [comment]
Closing this, as I think the focus should be on creating reusable containers rather than AWS AMIs
