### ISSUE TITLE
missing config.yml when running `docker-compose up`

### ISSUE THREAD

**Issue by michielbdejong** [trellis-ldp/trellis#380]
I followed https://github.com/trellis-ldp/trellis/wiki/Dockerized-Trellis and edited the `/local/...` paths to be existing paths on my machine, but then I ran into an error where it couldn't open config.yml.

Resolved this with `wget https://raw.githubusercontent.com/trellis-ldp/trellis/dbcd2b72dfa8c6133ef25acd84d3a711fe601495/platform/linux/src/docker/config.yml`

I guess the file is there in the Docker image, but /opt/trellis/etc gets overwritten with an empty folder when mounting the /local/trellis/etc from the host. There are a number of ways to fix this, for instance with a post-build bash command that creates the /opt/trellis/etc/config.yml if it doesn't exist.

Or shall I edit the wiki page to just mention that you should download a config.yml and put it in /local/trellis/etc yourself?

**Comment by michielbdejong** [comment]
ah, I now actually used [the Docker one](https://raw.githubusercontent.com/trellis-ldp/trellis/master/platform/server/src/docker/config.yml) as a basis and added this:
```sh
database:
  driverClass: org.postgresql.Driver
  user: changeme
  password: changeme
  url: jdbc:postgresql://db/db-name
```
to it from [the App Configuration Guide](https://github.com/trellis-ldp/trellis/wiki/App-Configuration-Guide), that seems to work so far!

**Comment by michielbdejong** [comment]
I guess  adding that in the config.yml makes the `TRELLIS_DB_`* env vars unnecessary.

**Comment by acoburn** [comment]
You are correct, the `TRELLIS_*` environment variables are primarily used to customize the fields in `config.yml`. So if you are overriding `config.yml`, then the env vars are less useful.

**Comment by acoburn** [comment]
@michielbdejong to answer the original question -- you are correct in pointing out that the wiki suggests mounting `/local/trellis/etc`, yet that overwrites the default configuration files with an empty directory (and hence causes the docker image to fail to start). I think the wiki should indicate that, should you wish to manage the `./etc` directory yourself (in the host platform rather than in the docker image itself), you will need to fetch or otherwise create your own `config.yml` file in that directory prior to starting the docker container. Feel free to edit the wiki to that effect.

**Comment by michielbdejong** [comment]
Great, thanks!

**Comment by michielbdejong** [comment]
Fixed in https://github.com/trellis-ldp/trellis/wiki/Dockerized-Trellis/_compare/b43de41fef3b9f451203e66b06285e4085f57166...772b8ebee095ff61e5c0b0b39f15a0c85cec6b3a

**Comment by acoburn** [comment]
Thanks @michielbdejong! I added a brief note about that docker configuration to clarify what is needed when that local mapping is enabled.
