### ISSUE TITLE
Running ldp-testsuite locally against Docker

### ISSUE THREAD

**Issue by michielbdejong** [trellis-ldp/trellis#381]
Hi!
I'm running Trellis in a Docker container, exposing port 8080, then I try to run the 'basic' tests of [the trellis-ldp fork of ldp-testsuite](https://github.com/trellis-ldp/ldp-testsuite) and see this:

```sh
java -jar ../../w3c/ldp-testsuite/target/ldp-testsuite-0.2.0-SNAPSHOT-shaded.jar --basic
[...]
Total tests run: 61, Failures: 5, Skips: 21
```

It seems to be failing the following tests. Is that expected?

Failed Test Cases | Groups | Description of Test Method
-- | -- | --
BasicContainer-PublishConstraintsUnknownProp | [MUST] | LDP servers MUST publish any constraints on LDP clients’ ability to create or update LDPRs, by adding a Link header with rel='http://www.w3.org/ns/ldp#constrainedBy' [RFC5988] to all responses to requests which fail due to violation of those constraints.
BasicContainer-PostJsonLd | [MUST] | LDP servers SHOULD accept a request entity body with a request header of Content-Type with value of application/ld+json [JSON-LD].
MemberResource-PublishConstraintsUnknownProp | [MUST] | LDP servers MUST publish any constraints on LDP clients’ ability to create or update LDPRs, by adding a Link header with rel='http://www.w3.org/ns/ldp#constrainedBy' [RFC5988] to all responses to requests which fail due to violation of those constraints.
BasicContainer-PostContainer | [MUST] | When a successful HTTP POST request to an LDPC results in the creation of an LDPR, a containment triple MUST be added to the state of LDPC.
MemberResource-PutSimpleUpdate | [MUST] | LDP servers SHOULD allow clients to update resources without requiring detailed knowledge of server-specific constraints. This is a consequence of the requirement to enable simple creation and modification of LDPRs.

**Comment by acoburn** [comment]
The LDP testsuite makes a number of assumptions about the LDP server that lead to certain questionable test failures.

The `PublishConstrainsUnknownProp` test is a bit suspect, since the test suite is assuming that a particular unknown property causes a failure: in Trellis, there are no constraints on an arbitrary unknown property, so those tests don't trigger a failure, though a constrainedBy document is, in fact, published when such a failure does exist -- you'd need to provide a `ldp:insertedContentRelation` property on the basic container to get that error.

The `PostJsonLD` error is not correct. Trellis supports JSON-LD via POST. I think the error is with the LDP test suite and how it matches JSON-LD application types.

The `PostContainer` test is also wrong. The state of the LDP-C _does_ change and will include the ldp:contains triple. This may have to do with how the LDP test suite deals with ETags. The `PutSimpleUpdate` is also failing because the test suite assumes that all RDF resources respond with strong ETags.

There are a few [environment variables](https://github.com/trellis-ldp/trellis-docker-tests/blob/master/trellis-ext-db-compose.yml#L9) that need to be set to run the LDP test suite against Trellis. These environment variables will adjust certain runtime characteristics (e.g. whether RDF resources respond with strong vs. weak ETags, whether Memento headers contain date strings -- the LDP test suite can't handle ISO dates in header attributes, and whether PUT absolutely must be accompanied by an `If-Match` or related header)

This is the [LDP report](https://www.trellisldp.org/ldp/report/basic.html) that you _should_ see with Trellis basic containers.

**Comment by acoburn** [comment]
One more comment, since you were running the trellis fork of the LDP test suite. I had cleaned up my commits last week so that they were much clearer, but I inadvertently removed one change that was necessary for handling JSON-LD requests. I have re-added [that change](https://github.com/trellis-ldp/ldp-testsuite/commit/b0fa5fd72e7efdd019d953705d18bc133cda0e64) and the JSON-LD tests pass as before.

TBH, I don't understand what the `CustomTypeSafeMatcher` type is doing, but as defined in the LDP test suite, it doesn't work with JSON-LD documents.

**Comment by michielbdejong** [comment]
Thanks!!
