### ISSUE TITLE
hasAcl data

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#410]
There is currently no slot in `Metadata` for any value that could support `Resource::hasAcl`.

I'm not sure what the various backends are doing (besides `t-c*`, which is doing nothing, which is how @gregjan spotted this) but presumably they are recording this in some way. Our pattern has been to drive such information into `Metadata` so that every backend can receive it without having to rewrite the same logic. Can we take that approach here?

**Comment by acoburn** [comment]
Adding this to the `Metadata` object makes a lot of sense to me.

**Comment by ajs6f** [comment]
I'll send a PR with the changes to `Metadata`, but I'm not entirely sure where to find the info in question to add something to `-http` to fill the slot. Is there a good example to look at? I assume you're munging triples to do it now in the backends?

**Comment by ajs6f** [comment]
Hoy @acoburn Is [this](https://github.com/trellis-ldp/trellis/blob/master/components/file/src/main/java/org/trellisldp/file/FileResource.java#L113) a good place to take as a model for how to find the `hasAcl` info? Could I have the various HTTP method handlers look in the quads for that graph and derive a `hasAcl` value therefrom?

**Comment by acoburn** [comment]
For all of the mutating HTTP methods, you'll have an entire `Dataset` ready at hand, and so you should be able to just do something like

    boolean hasAcl = dataset.getGraph(Trellis.PreferAccessControl)
            .flatMap(graph -> graph.stream().findAny()).isPresent()

You can add that logic to [this method](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java#L255-L268), which will make sure that the value is available to a backend via the `Metadata` object.

It would be nice to eventually adjust the triplestore implementation so that it can make use of this value, but let's do that separately; I'd like to be careful about how we manage changes to the data layout.

**Comment by ajs6f** [comment]
Well, that's validating-- I had already altered that method as a first guess, so I'll just send that commit!

**Comment by acoburn** [comment]
Resolved via #412
