### ISSUE TITLE
Rename Resource interface to LdpResource

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#438]
This will make the conversion to Jena types easier, since Jena also has a `Resource` interface.

An alternative name could be `TrellisResource`.

**Comment by ajs6f** [comment]
I'm voting for `RDFSource`, to keep the focus on LDP.

**Comment by acoburn** [comment]
I like `RDFSource`, too, but I thought it would be confusing in the case where the object represents a `NonRDFSource`. I.e.:

```java
RDFSource resource = ...;
LDP.NonRDFSource == resource.getInteractionModel();
```

Though one could possibly think about it in terms of _every_ resource really being an `RDFSource`, though some of those have attached binaries (which is sort of the structure we have in place with the Java API).

Really, it's an `RDFBearingResource`, which may be either an LDP NonRDFSource or an LDP RDFSource (or one of its subtypes). If you would like to see this be `RDFSource`, that's fine with me, but we'd just need to make sure that the documentation is sufficiently clear about the LDP types. This is why I suggest `LdpResource`, since it can have any of the LDP interaction models.

**Comment by acoburn** [comment]
If we call this interface `RDFSource`, should we also change ResourceService to something like RDFService? Or shall we keep ResourceService as it is?

**Comment by ajs6f** [comment]
I'd like to think through `RDFBearingResource` for a moment, if we have time. It seems to me that we are facing the fact that we have (current) `Resource`s and `Binary`s but the actual HTTP behavior of a real LDP Non-RDF Source requires one of each, because of the choices we've made with respect to `description`. We don't have a thing like that, that is or has both. Instead, a `Resource` has a `Binary`. `RDFBearingResource` would be that thing.  In that sense, it would be a real LDP `Resource`, whereas current Trellis `Resource` is really an LDP `RDFSource` and current Trellis `Binary` is really an LDP `NonRDFSource`. `RDFBearingResource` would be the real LDP `Resource` because we can use the assumption that all Trellis binaries have descriptions to infer that all LDP `Resource`s must be Trellis `RDFBearingResource`s, and certainly all Trellis `RDFBearingResource`s are LDP `Resource`s.

That is pretty confusing stuff to me, but my ultimate claim is that we _could_ introduce an `RDFBearingResource` class and we should call it `LDPResource`, we should change current Trellis `Resource` to `RDFSource < RDFBearingResource` (and `RDFSource` may add almost nothing, which is fine) and current `Binary` should become `NonRDFSource < RDFBearingResource`.

This would reverse what we have now, in which a current Trellis `Resource` can have a `Binary`. We would be saying that (future) `RDFSource`s do _not_ have (future) `NonRDFSource`s, instead (future) `NonRDFSource`s have RDF descriptions accessed via their  (future) `Resource` (= proposed `RDFBearingResource`) type. I think we could set up a default arrangement in which those descriptions are just stored as additional `LDPResource`s and the only information that would need to persist with a `NonRDFSource` would be an URI for that description (normally Trellis-canonical `blah?ext=description`).

Do you see what I mean? Put very shortly, I mean that we are calling the wrong thing "Resource", because we are currently distinguishing "things that _are_ RDF" from things that _are_ RDF and _have_ a thing that is not" from "things that are not RDF" and what we really want to do is to distinguish "things that have RDF" from "things that have RDF and more", because in fact there is no HTTP URI in a Trellis system that does not have RDF associated with it.

Obviously, this would blow up a bunch of impl code. :weary:

**Comment by acoburn** [comment]
I think part of the issue is that LDP is, fundamentally, an HTTP abstraction. The Trellis API tries to structure primitives that are useful in creating those LDP abstractions, though the interfaces, in themselves, don't provide the HTTP-layer features (hence the separation of `trellis-api` and `trellis-http`).

In that sense, I'm not too concerned about replicating the exact HTTP abstractions and semantics at the API layer -- the two are related but don't need to be exactly the same. Following that argument forward would suggest _not_ using `RDFSource` as an interface name, but something more generic, e.g. `TrellisResource` that sits underneath the LDP abstractions.

**Comment by ajs6f** [comment]
> the interfaces, in themselves, don't provide the HTTP-layer features

Well, no, that's my point-- they very much do provide the only HTTP feature we care about here: the coupling between `NonRDFSource`s and their `description`s. You can get a `Binary` from a `Resource`, and you can do that _precisely_ in order to couple a `NonRDFSource` and a `RDFSource` together in HTTP. That is exactly what `Resource::getBinaryMetadata` _means_.

I'm saying we are _already_ "replicating the … HTTP abstractions and semantics at the API layer", but wrongly. I'm not going to push wholesale change here, but I don't think current Trellis `Resource` can correctly be renamed to `LDPResource`. In a very practical sense, a current Trellis `Resource` must be able to produce RDF and an LDP `Resource` needn't. That's a pretty serious difference in behavior that we would be eliding by using the name `LDPResource`.

**Comment by acoburn** [comment]
With the upcoming Jena 3.15 release, we will be able to use the Jena-managed Commons RDF implementation directly, which will eliminate all the issues we have with using the commons-rdf-jena module.
