### ISSUE TITLE
Review service injection mechanisms

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#441]
At present, there are two principle mechanisms in use for service injection: `ServiceLoader` and `@Inject`. We should discuss how services should be injected throughout the code in order to make this work more consistently. See [this discussion](https://github.com/trellis-ldp/trellis/pull/435#discussion_r305872716) for more context.

The following services are currently injected via the `ServiceLoader`:

* All Commons-RDF injection (to be removed in #358)
* Injection of ConstraintRules in the [http-layer](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/impl/BaseLdpHandler.java#L46) -- we should be able to support multiple service implementations here
* Injection of TimemapGenerator in the [http-layer](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/impl/MementoResource.java#L331-L334) -- here we use an anonymous impl of this interface
* Injection of ETagGenerator in the http-layer (see #435)
* Injection of IdentifierService (throughout)
* Injection of ActivityStreamService (in the notification implementations)

`@Inject` is used elsewhere, but there is no clear way we are distinguishing between these two categories (though for Commons-RDF using the `ServiceLoader` is the preferred mechanism)

**Comment by ajs6f** [comment]
It seems to me that another way to ask this question is: are we willing to commit to CDI throughout Trellis? If yes, we should use `@Inject` everywhere because there is no advantage to `ServiceLoader` then. If not, we should not rely on `@Inject` at all, so every injection point should feature some way to avoid using injection (the easy obvious way to is to use ctor injection all the time). I'm not sure what `ServiceLoader` adds in that case too, at least that we couldn't buy ready-built-- it seems like a way to have a default choice for a wiring slot that can be overridden, which is exactly the function of a wiring framework.

**Comment by acoburn** [comment]
Thus far we have had success with constructor injection. This has the added advantage that everything also works in non-CDI environments (e.g. Dropwizard or Spring Boot). This also makes unit testing a lot easier.

In principle, I suspect that we could just add slots for most of these in the `ServiceBundler` interface. The `ActivityStreamService` interface could be added to the various notification constructors.

**Comment by ajs6f** [comment]
That would work for me. It would also give us a nice place (`ServiceBundler`) to send people who want to use a new wiring framework.

**Comment by acoburn** [comment]
At this point, all of what I would term "core" service injection (except Commons-RDF) happens via the `ServiceBundler` interface. There are other instances of injection, but those are all implementation specific: e.g. the `FileBinaryService` uses the `ServiceLoader` to look up an `IdentifierService` (as does the `TriplestoreResourceService`. That is, everything else falls well outside the scope of the `ServiceBundler`

@ajs6f do you think we can close this issue or shall we keep working on some of those component-level instances? (I am inclined to view those as "implementation details" and just close this ticket)

**Comment by ajs6f** [comment]
Do I understand the resolution here to be: components that are required for operation are always to be available from `ServiceBundler` and otherwise, we have no opinion? I'm not entirely comfortable with that. I would prefer to have _all_ of the components available in the _same_ way, without regard to their scope or optionality. Anything else, it seems to me, is not optimal for introducing new developers.

How about this:

We use ctor injection for _all_ components within Trellis. If someone wants to use `ServiceLoader`, they need merely connect it to their app and whatever framework it is using, if any. E.g., you are using Spring; then  just use [`ServiceLoaderFactoryBean`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/serviceloader/ServiceLoaderFactoryBean.html). [CDI](https://docs.jboss.org/weld/reference/latest/en-US/html/extend.html#_registering_a_bean) isn't any more difficult, and I would be happy to show an example in the [µprofile app](https://github.com/trellis-ldp/trellis-micro). When I ever get around to making any more time to work on it. :grumble:

Of course, anyone needs to do that for themselves, _only if they actually want to use `ServiceLoader`_, which is a better state of affairs, from my POV. `ServiceLoader` is the source, as you'll know, of a lot of problems for people using build tools because it requires some smart shading within artifacts to get everything coupled up.

Another way to say this is that I find it very hard to believe that anyone is going to prefer building up their own app using `ServiceLoader` over using an injection framework. And how about using a standard DI framework BUT WAIT NOT FOR THIS SPECIAL COMPONENT OVER HERE THAT'S DIFFERENT FOR NO OBVIOUS REASON? Frankly, I want to encourage people to use off-the-shelf parts . What was the last time you discarded "off-the-shelf" DI in favor of rolling your own? Do we actually have a use case (right now!) for DI-less operation?

If preferring ctor injection would disallow the use of `ServiceLoader` or would mung the code, this would be a different question. But it doesn't do either. The code would be, if anything, _cleaner_. Just ctors, with no generic utility methods capable of producing any type at all callable from any site (they're `static`, after all, and one way to say `static` is to say "Can be called from any point in the code."). It just moves the interaction with `ServiceLoader` from inside the Trellis framework to the application using it, which I would say is a better place for any function that isn't likely to be useful to most users. 

So… my choice would be to close this ticket in favor of one that asks to ensure that _all_ components can be supplied in ctors, period. (We needn't say anything about injection, per se. Just ctors.)

**Comment by acoburn** [comment]
@ajs6f I agree on removing use of the `ServiceLoader`. I'll work up a PR that removes any remaining parts of that.
