### ISSUE TITLE
Implement an EventService using MP reactive messaging

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#483]
Microprofile provides a generic message processing system with [reactive streams](https://github.com/eclipse/microprofile-reactive-messaging/blob/master/spec/src/main/asciidoc/architecture.asciidoc). There is a more complete description on the [SmallRye website](https://smallrye.io/smallrye-reactive-messaging/).

This would likely be an easy way to integrate an `EventService` component into a microprofile-based application while also being generic across message brokers.

**Comment by ajs6f** [comment]
The way I'm reading it (late on Friday, mind you) it looks like a good _replacement_ for `EventService`. We would annotate the framework code as shown and instead of having (say) a JMS module that impls `EventService`, it would `@Incoming` a (or more than one, TBD) from the framework and kick out JMS. To be sure, that is a really strong dependency on µprofile, but it's also isolated within this part of the framework.

My only immediate concern would be that it looks like streams have hard-coded names, which feels a bit weird to me. But if the names of those streams stay entirely inside the framework and components, I don't know why I would care.

How do you see it?

**Comment by acoburn** [comment]
Yes, eventually this could very well _replace_ the other event service implementations. I'd want some more real-world experience with this before making that move, but this seems somewhat similar in how we've moved entirely to microprofile-config throughout the codebase.

w/r/t the hard-coded names, I was thinking that, with a bit of µP-config work, we could make those names configurable.

**Comment by ajs6f** [comment]
Yeah, there's the rub. It's not trivial for us to compare real-world performance this early. What do you think about trying to set up something on the UMD testbed? Eventing is a part of performance. @gregjan, WDYT? And then, what exactly would that tell us?

**Comment by gregjan** [comment]
Since I am fighting our @Default vs. NoopEventService CDI pattern right now in trellis-cassandra, this idea seems beneficial. I'm all for shoving as much wiring into the runtime platform as possible. Testing alternatives take me an hour or so, I imagine and might be well worth it.

**Comment by ajs6f** [comment]
@gregjan, if you having trouble with getting the right bean up in `t-c*`, can you file a ticket on it to that specific problem? I seem to remember this happening before, so let's get it fixed once and for all.

**Comment by gregjan** [comment]
I think I've figured out that beans.xml was loading the NoopEventService.. Testing it.

**Comment by gregjan** [comment]
That was it, btw.

**Comment by ajs6f** [comment]
Excellent! :fireworks:
