### ISSUE TITLE
Build cycle

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#93]
I'm not sure when this showed up (haven't looked at the code in a few days) but I'm getting a weird Eclipse error:
```
A cycle was detected in the build path of project 'trellis-test'. The cycle consists of projects {trellis-test, trellis-triplestore}
```
(of course it shows up for `-triplestore` too). The CLI `./gradlew` build works fine. It appears to be a dependency cross via the `testCompile` scope. Is this considered a problem in Gradle builds? I really have no idea.

**Comment by acoburn** [comment]
The issue is that the main classes of `trellis-test` are used in the test scope of `trellis-triplestore`, but in the test phase of `trellis-test`, I'm checking the main classes of `trellis-triplestore` to verify them with Pax-Exam. This isn't a problem for gradle since it just compiles all the projects first and only then runs the tests.

That said, it would be easy to just move the `OSGiTest` in `trellis-test` into its own module (e.g. `trellis-osgi`). In fact, I'll plan on doing just that.

**Comment by ajs6f** [comment]
Thanks, I'm somewhat blocked on #91 by this-- I can fix everything above and below `-triplestore`, but not it.
